spring.application.name=geosentinel



server.servlet.context-path=/api/v1



spring.datasource.url=jdbc:postgresql://localhost:5432/GeoSentinel
spring.datasource.username=postgres
spring.datasource.password=database


spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true